name: "Hello Actions"
description: "Greeting someone"
author: "octocat@github.com"

inputs:
  MY_NAME:
    description: "Who to greet"
    required: true
    default: "World"
    
runs:
  using: "docker"
  iamge: "Dockerfile"
  
branding:
  icon: "mic"
  color: "purple"
